/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignments.a1;

import org.junit.jupiter.api.Test;

import assignments.Main;

import static org.junit.jupiter.api.Assertions.*;

class a1Test {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
