/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignments.a1;

import org.junit.jupiter.api.Test;

import static assignments.a1.MathUtils.*;

import static org.junit.jupiter.api.Assertions.*;


public class MathUtilsTest {
    private static Integer max = Integer.MAX_VALUE;
    private static Integer max_minus_one = Integer.MAX_VALUE - 1;
    private static Integer mid1 = 25;
    private static Integer mid2 = 31;

    @Test
    public void testZerosAndMax() {
        assertEquals(0, lcm(0, 0));
        assertEquals(0, lcm(0, max));
        assertEquals(0, lcm(max, 0));
    }

    @Test
    public void testBoundariesMinusOne() {
        assertEquals(max_minus_one, lcm(1, max_minus_one));
        assertEquals(max_minus_one, lcm(max_minus_one, 1));
    }
    @Test
    public void testPrimes() {
        assertEquals(775, lcm(mid1, mid2));
        assertEquals(775, lcm(mid2, mid1));
        assertEquals(mid1, lcm(mid1, mid1));
    }
    @Test
    public void testMaxAndMax() {
        assertEquals(max, lcm(max, max));
    }

    @Test
    public void testOverflow() {
        assertTrue((max % lcm(max, max_minus_one) != 0 || max_minus_one % lcm(max, max_minus_one) != 0));
        assertTrue((max % lcm(max_minus_one, max) != 0 || max_minus_one % lcm(max_minus_one, max) != 0));
    }
}